main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('zergs/', views.zergs_index, name='index'),
    path('zergs/<int:zerg_id>/', views.zergs_detail, name='detail'),
    path('zergs/create/', views.ZergCreate.as_view(), name='zergs_create'),
    path('zergs/<int:pk>/update/', views.ZergUpdate.as_view(), name='zergs_update'),
    path('zergs/<int:pk>/delete/', views.ZergDelete.as_view(), name='zergs_delete'),
    path('zergs/<int:zerg_id>/add_essence/', views.add_essence, name='add_essence'),
    path('enemies/', views.EnemyList.as_view(), name='enemies_index'),
    path('zergs/<int:zerg_id>/assoc_enemy/<int:enemy_id>/', views.assoc_enemy, name='assoc_enemy'),
    path('enemies/<int:pk>/', views.EnemyDetail.as_view(), name='enemies_detail'),
    path('enemies/create/', views.EnemyCreate.as_view(), name='enemies_create'),
    path('enemies/<int:pk>/update/', views.EnemyUpdate.as_view(), name='enemies_update'),
    path('enemies/<int:pk>/delete/', views.EnemyDelete.as_view(), name='enemies_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('zergs/<int:zerg_id>/add_photo/', views.add_photo, name='add_photo'),
]

zergcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

ABSORBTIONS = (
    ('S', 'Small'),
    ('M', 'Medium'),
    ('L', 'Large'),
)

RACES = (
    ('T', 'Terran'),
    ('P', 'Protoss'),
    ('Z', 'Zerg'),
)

# Create your models here.

class Enemy(models.Model):
    name = models.CharField(max_length=50)
    race = models.CharField(max_length=1,
        choices=RACES,
        default=RACES[0][0]
        )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('enemies_detail', kwargs={'pk': self.id})


class Zerg(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    minerals = models.IntegerField()
    vespene = models.IntegerField()
    enemies = models.ManyToManyField(Enemy)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'zerg_id': self.id})

class Essence(models.Model):
    date = models.DateField('Absorbtion Date')
    absorbtions = models.CharField(
        max_length=1,
        choices=ABSORBTIONS,
        default=ABSORBTIONS[0][0]
    )

    zerg = models.ForeignKey(Zerg, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.get_absorbtions_display()} on {self.date}"

    class Meta:
        ordering = ['-date']

class Photo(models.Model):
    url = models.CharField(max_length=200)
    zerg = models.ForeignKey(Zerg, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for zerg_id: {self.zerg_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Essence

class EssenceForm(ModelForm):
  class Meta:
    model = Essence
    fields = ['date', 'absorbtions']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Enemy, Zerg, Enemy, Photo
from .forms import EssenceForm
import uuid
import boto3
import os


# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def zergs_index(request):
    zergs = Zerg.objects.filter(user=request.user)
    return render(request, 'zergs/index.html', { 'zergs': zergs })

@login_required
def zergs_detail(request, zerg_id):
    zerg = Zerg.objects.get(id=zerg_id)
    id_list = zerg.enemies.all().values_list('id')
    enemis_zerg_doesnt_have = Enemy.objects.exclude(id__in=id_list)
    essence_form = EssenceForm()
    return render(request, 'zergs/detail.html', {
        'zerg': zerg, 'essence_form': essence_form,
        'enemies': enemis_zerg_doesnt_have
    })

@login_required
def add_essence(request, zerg_id):
  form = EssenceForm(request.POST)
  if form.is_valid():
    new_essence = form.save(commit=False)
    new_essence.zerg_id = zerg_id
    new_essence.save()
  return redirect('detail', zerg_id=zerg_id)

@login_required
def assoc_enemy(request, zerg_id, enemy_id):
  Zerg.objects.get(id=zerg_id).enemies.add(enemy_id)
  return redirect('detail', zerg_id=zerg_id)

class EnemyList(LoginRequiredMixin, ListView):
  model = Enemy

class EnemyDetail(LoginRequiredMixin, DetailView):
  model = Enemy

class EnemyCreate(LoginRequiredMixin, CreateView):
  model = Enemy
  fields = '__all__'

class EnemyUpdate(LoginRequiredMixin, UpdateView):
  model = Enemy
  fields = ['name', 'race']

class EnemyDelete(LoginRequiredMixin, DeleteView):
  model = Enemy
  success_url = '/enemies/'

class ZergCreate(LoginRequiredMixin, CreateView):
    model = Zerg
    fields = ['name', 'description', 'minerals', 'vespene']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class ZergUpdate(LoginRequiredMixin, UpdateView):
    model = Zerg
    fields = ['description', 'minerals', 'vespene']

class ZergDelete(LoginRequiredMixin, DeleteView):
    model = Zerg
    success_url = '/zergs/'

def add_photo(request, zerg_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Photo.objects.create(url=url, zerg_id=zerg_id)
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('detail', zerg_id=zerg_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

    <h1>About the Zerg Collector</h1>
    <hr />
    <p>Your one stop shop for the vast Zerg Swarm!  This collector helps keep track of the Zerg Swarm, and its enemies, from the universe of StarCraft and StarCraft 2.</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Zerg Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;ZergCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'zergs_create' %}">Add a Zerg</a></li>
            <li><a href="{% url 'index' %}">View All Zerg</a></li>
            <li><a href="{% url 'enemies_create' %}">Add an Enemy</a></li>
            <li><a href="{% url 'enemies_index' %}">View All Enemies</a></li> 
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
              <li><a href="{% url 'signup' %}">Sign Up</a></li>  
              <li><a href="{% url 'login' %}">Log In</a></li>
            {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 Zerg Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/enemy_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Enemy</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'enemies_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/enemy_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Enemy Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ enemy.get_name_display }}</span>
        <p>Race: {{ enemy.get_race_display }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'enemies_update' enemy.id %}">Edit</a>
        <a href="{% url 'enemies_delete' enemy.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/enemy_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Enemy</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/enemy_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Enemy List</h1>

{% for enemy in enemies_list %}
  <a href="{% url 'enemies_detail' enemy.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ enemy.get_name_display }}</span>
            <p>Race: {{ enemy.get_race_display }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/zerg_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Zerg</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' zerg.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/zerg_form.html
{% extends 'base.html' %}

{% block content %}
    {% if object %}
        <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
    {% else %}
        <h1>Add Zerg</h1>
    {% endif %}
        <form action="" method="POST">
            {% csrf_token %}
            <table>
            {{ form.as_table }}
            </table>
            <input type="submit" value="Submit!" class="btn">
        </form>
{% endblock %}

main_app/templates/zergs/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Zerg Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
      <span class="card-title">{{ zerg.name }}</span>
      <p>Description: {{ zerg.description|linebreaks }}</p>
      <p>Minerals: {{ zerg.minerals }}</p>
      {% if zerg.vespene > 0 %}
          <p>Vespene: {{ zerg.vespene }}</p>
      {% else %}
          <p>No Vespene Cost</p>
      {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'zergs_update' zerg.id %}">Edit</a>
        <a href="{% url 'zergs_delete' zerg.id %}">Delete</a>
      </div>
    </div>
    {% for photo in zerg.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' zerg.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <input type="submit" class="btn" value="Upload Photo">
    </form>
  </div>
  <div class="col s6">
    <form action="{% url 'add_essence' zerg.id %}" method="POST">
      {% csrf_token %}
      {{ essence_form.as_p }}
      <input type="submit" class="btn" value="Add Essence">
    </form>  
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Absorbtion</th></tr>
      </thead>
      <tbody>
        {% for essence in zerg.essence_set.all %}
          <tr>
            <td>{{essence.date}}</td>
            <td>{{essence.get_absorbtions_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ zerg.name }}'s Enemies</h3>
    {% if zerg.enemies.count %}
      {% for enemy in zerg.enemies.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A {{ enemy.get_race_display }} <span>{{ enemy.name }}</span> 
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Enemies >:D</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
  <div class="col s6">
  <h3>Available Enemies</h3>
  {% if enemies.count %}
    {% for enemy in enemies.all %}
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            A {{ enemy.get_race_display }} <span>{{ enemy.name }}</span>
          </span>
        </div>
        <div class="card-action">
          <form action="{% url 'assoc_enemy' zerg.id enemy.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn">Add</button>
          </form>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <h5>{{zerg.name}} Already Has All Enemies Available</h5>
  {% endif %}
</div>


<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const selectEl = document.getElementById('id_absorbtions');
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/zergs/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Zerg List</h1>

{% for zerg in zergs %}
  <div class="card">
    <a href="{% url 'detail' zerg.id %}">
      <div class="card-content">
        <span class="card-title">{{ zerg.name }}</span>
        <p>Description: {{ zerg.description }}</p>
        <p>Minerals: {{ zerg.minerals }}</p>
        {% if zerg.vespene > 0 %}
          <p>Vespene: {{ zerg.vespene }}</p>
        {% else %}
          <p>No Vespene Cost</p>
        {% endif %}
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}